meta_product_name: "talktoo"
meta_title: "talktoo - talk the talk"
meta_description: "Talk the talk. Foreign language practice for busy professionals."
meta_image: "app/assets/images/ogimage.jpeg"
# meta_image: "https://images.unsplash.com/photo-1517940001917-1c03b8b1b85b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1039&q=80" # should exist in `app/assets/images/`
