meta_product_name: "talktoo"
meta_title: "talktoo - talk the talk"
meta_description: "Talk the talk. Foreign language practice for busy professionals."
meta_image: "ogimage.jpeg" # should exist in `app/assets/images/`
